import { RawVariant } from '@/types/genomics';

export function generateBenchmarkSampleVariants(): {
  header: string[];
  variants: RawVariant[];
} {
  const header = [
    '# This data file generated by 23andMe at: Fri Oct 14 09:12:44 2022',
    '# Reference Genome: build 38 (GRCh38)',
    '# More information on reference human assembly build 38: http://www.ncbi.nlm.nih.gov/projects/genome/assembly/grc/human/',
    '# rsid\tchromosome\tposition\tgenotype',
  ];

  const variants: RawVariant[] = [
    // --- PGx Actionable Loci ---
    // CYP2C19 *1/*2 (Intermediate Metabolizer -> clopidogrel resistance)
    { rsid: 'rs4244285', chromosome: '10', position: 94781859, genotype: 'AG' },
    { rsid: 'rs4986893', chromosome: '10', position: 94775416, genotype: 'GG' },
    { rsid: 'rs12248560', chromosome: '10', position: 94761900, genotype: 'CC' },

    // SLCO1B1 *1/*5 (Intermediate Transporter -> Statin Myopathy Risk)
    { rsid: 'rs4149056', chromosome: '12', position: 21178615, genotype: 'TC' },

    // CYP2C9 & VKORC1 (Warfarin Sensitive)
    { rsid: 'rs1799853', chromosome: '10', position: 94942293, genotype: 'CT' }, // *2 carrier
    { rsid: 'rs1057910', chromosome: '10', position: 94981296, genotype: 'AA' },
    { rsid: 'rs9923231', chromosome: '16', position: 31096368, genotype: 'TT' }, // VKORC1 high sensitivity

    // DPYD (Normal)
    { rsid: 'rs3918290', chromosome: '1', position: 97450058, genotype: 'GG' },
    { rsid: 'rs67376798', chromosome: '1', position: 97883344, genotype: 'AA' },

    // --- ClinVar Rare / Pathogenic Markers ---
    // HFE C282Y Heterozygous Carrier
    { rsid: 'rs1800562', chromosome: '6', position: 26093141, genotype: 'GA' },
    { rsid: 'rs1799945', chromosome: '6', position: 26091179, genotype: 'CC' },

    // Factor V Leiden (Normal)
    { rsid: 'rs6025', chromosome: '1', position: 169519049, genotype: 'CC' },

    // Prothrombin (Normal)
    { rsid: 'rs1799963', chromosome: '11', position: 46739492, genotype: 'GG' },

    // Alpha-1 Antitrypsin Pi*S Carrier
    { rsid: 'rs17580', chromosome: '14', position: 94378610, genotype: 'AT' },
    { rsid: 'rs28929474', chromosome: '14', position: 94380904, genotype: 'CC' },

    // --- PRS Coronary Artery Disease ---
    { rsid: 'rs10757274', chromosome: '9', position: 22124477, genotype: 'GG' },
    { rsid: 'rs1333049', chromosome: '9', position: 22115503, genotype: 'CC' },
    { rsid: 'rs6903956', chromosome: '6', position: 12903930, genotype: 'AG' },
    { rsid: 'rs20455', chromosome: '1', position: 109817590, genotype: 'AG' },
    { rsid: 'rs17465637', chromosome: '1', position: 64796338, genotype: 'CC' },
    { rsid: 'rs1122608', chromosome: '19', position: 11200088, genotype: 'TG' },
    { rsid: 'rs9982601', chromosome: '21', position: 35677370, genotype: 'CC' },
    { rsid: 'rs646776', chromosome: '1', position: 109822166, genotype: 'TT' },

    // --- PRS Type 2 Diabetes ---
    { rsid: 'rs7903146', chromosome: '10', position: 114758349, genotype: 'CT' },
    { rsid: 'rs1801282', chromosome: '3', position: 12393125, genotype: 'CC' },
    { rsid: 'rs5219', chromosome: '11', position: 17409572, genotype: 'TT' },
    { rsid: 'rs7756992', chromosome: '6', position: 20680193, genotype: 'AG' },
    { rsid: 'rs9939609', chromosome: '16', position: 53820527, genotype: 'AA' },
    { rsid: 'rs10830963', chromosome: '11', position: 92708710, genotype: 'CG' },

    // --- PRS Breast Cancer ---
    { rsid: 'rs2046210', chromosome: '6', position: 152010271, genotype: 'GA' },
    { rsid: 'rs3803662', chromosome: '16', position: 52599187, genotype: 'CC' },
    { rsid: 'rs13387042', chromosome: '2', position: 217937517, genotype: 'AG' },
    { rsid: 'rs2981582', chromosome: '10', position: 123354729, genotype: 'CT' },
    { rsid: 'rs1219648', chromosome: '10', position: 123357972, genotype: 'GG' },
    { rsid: 'rs4784227', chromosome: '16', position: 52598159, genotype: 'CT' },

    // --- PRS Atrial Fibrillation ---
    { rsid: 'rs2200733', chromosome: '4', position: 111450201, genotype: 'CT' },
    { rsid: 'rs10033464', chromosome: '4', position: 111440871, genotype: 'TT' },
    { rsid: 'rs2106261', chromosome: '16', position: 73002283, genotype: 'CC' },
    { rsid: 'rs13376333', chromosome: '1', position: 154823901, genotype: 'TC' },

    // --- PRS Alzheimer's / APOE ---
    { rsid: 'rs429358', chromosome: '19', position: 44908684, genotype: 'TC' }, // APOE e3/e4
    { rsid: 'rs7412', chromosome: '19', position: 44908822, genotype: 'CC' },
    { rsid: 'rs6733839', chromosome: '2', position: 127891244, genotype: 'TC' },
    { rsid: 'rs11136000', chromosome: '8', position: 27464041, genotype: 'TT' },
    { rsid: 'rs3851179', chromosome: '11', position: 85934500, genotype: 'CC' },

    // --- GWAS Curated Traits ---
    { rsid: 'rs762551', chromosome: '15', position: 74749576, genotype: 'AA' }, // Fast caffeine metabolizer
    { rsid: 'rs4988235', chromosome: '2', position: 135851076, genotype: 'AG' }, // Lactase persistent
    { rsid: 'rs671', chromosome: '12', position: 111803962, genotype: 'GG' }, // Normal alcohol
    { rsid: 'rs1815739', chromosome: '11', position: 66560624, genotype: 'CT' }, // Mixed muscle fiber
    { rsid: 'rs713598', chromosome: '7', position: 141972804, genotype: 'GG' }, // Super taster
    { rsid: 'rs1801260', chromosome: '4', position: 55452331, genotype: 'TT' }, // Morning lark
    { rsid: 'rs5082', chromosome: '1', position: 161222292, genotype: 'CC' }, // High sat fat sensitivity

    // Chip v5 Fingerprints
    { rsid: 'rs76735552', chromosome: '1', position: 155205634, genotype: 'TT' },
    { rsid: 'rs143360432', chromosome: '3', position: 49352941, genotype: 'CC' },
  ];

  // Fill synthetic background autosomal SNPs for realistic QC metrics
  for (let chr = 1; chr <= 22; chr++) {
    for (let j = 0; j < 300; j++) {
      const isHet = j % 3 === 0;
      const gt = isHet ? 'AG' : 'AA';
      variants.push({
        rsid: `rs_syn_${chr}_${j}`,
        chromosome: `${chr}`,
        position: 1000000 + j * 500000,
        genotype: gt,
      });
    }
  }

  return { header, variants };
}
