import { ClinVarRecord } from '@/types/genomics';

export const CURATED_CLINVAR_RECORDS: ClinVarRecord[] = [
  {
    rsid: 'rs1800562',
    gene: 'HFE',
    variantDescription: 'p.Cys282Tyr (C282Y)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Hereditary Hemochromatosis Type 1 (Autosomal Recessive)',
    acmgClassification: 'Tier 1',
    pubmedIds: ['8696333', '10973841', '12444983'],
    clinvarId: 'VCV000000009',
    riskAllele: 'A',
  },
  {
    rsid: 'rs1799945',
    gene: 'HFE',
    variantDescription: 'p.His63Asp (H63D)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 3,
    reviewStatus: 'Reviewed by expert panel',
    associatedCondition: 'Hereditary Hemochromatosis Modifier (Low Penetrance)',
    acmgClassification: 'Tier 2',
    pubmedIds: ['8696333', '11830492'],
    clinvarId: 'VCV000000010',
    riskAllele: 'G',
  },
  {
    rsid: 'rs6025',
    gene: 'F5',
    variantDescription: 'p.Arg506Gln (Factor V Leiden)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Hereditary Thrombophilia / Deep Vein Thrombosis',
    acmgClassification: 'Tier 1',
    pubmedIds: ['7954848', '8401533', '11438528'],
    clinvarId: 'VCV000000119',
    riskAllele: 'A', // C is normal, T (or A on reverse/forward depending on strand) -> G>A on forward
  },
  {
    rsid: 'rs1799963',
    gene: 'F2',
    variantDescription: 'c.*97G>A (Prothrombin G20210A)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Prothrombin-related Thrombophilia',
    acmgClassification: 'Tier 1',
    pubmedIds: ['8896563', '11384978'],
    clinvarId: 'VCV000000120',
    riskAllele: 'A',
  },
  {
    rsid: 'rs28929474',
    gene: 'SERPINA1',
    variantDescription: 'p.Glu366Lys (Pi*Z allele)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Alpha-1 Antitrypsin Deficiency (Emphysema, Liver Cirrhosis)',
    acmgClassification: 'Tier 1',
    pubmedIds: ['6604473', '12053075'],
    clinvarId: 'VCV000000127',
    riskAllele: 'T',
  },
  {
    rsid: 'rs17580',
    gene: 'SERPINA1',
    variantDescription: 'p.Glu288Val (Pi*S allele)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 3,
    reviewStatus: 'Reviewed by expert panel',
    associatedCondition: 'Alpha-1 Antitrypsin Deficiency (Mild / Compound Risk)',
    acmgClassification: 'Tier 2',
    pubmedIds: ['2023961', '12053075'],
    clinvarId: 'VCV000000128',
    riskAllele: 'T',
  },
  {
    rsid: 'rs80357906',
    gene: 'BRCA1',
    variantDescription: 'c.68_69delAG (185delAG)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Hereditary Breast and Ovarian Cancer Syndrome (HBOC)',
    acmgClassification: 'ACMG Secondary Finding',
    pubmedIds: ['7573030', '16489001'],
    clinvarId: 'VCV000017658',
    riskAllele: 'D',
  },
  {
    rsid: 'rs80357713',
    gene: 'BRCA1',
    variantDescription: 'c.5266dupC (5382insC)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Hereditary Breast and Ovarian Cancer Syndrome (HBOC)',
    acmgClassification: 'ACMG Secondary Finding',
    pubmedIds: ['7573030', '9145677'],
    clinvarId: 'VCV000017684',
    riskAllele: 'I',
  },
  {
    rsid: 'rs80359550',
    gene: 'BRCA2',
    variantDescription: 'c.5946delT (6174delT)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Hereditary Breast and Ovarian Cancer Syndrome (HBOC)',
    acmgClassification: 'ACMG Secondary Finding',
    pubmedIds: ['8644709', '11896585'],
    clinvarId: 'VCV000052787',
    riskAllele: 'D',
  },
  {
    rsid: 'rs113488022',
    gene: 'BRAF',
    variantDescription: 'p.Val600Glu (V600E)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Cardiofaciocutaneous syndrome / Somatic Melanoma Susceptibility',
    acmgClassification: 'Tier 1',
    pubmedIds: ['12068308', '16439621'],
    clinvarId: 'VCV000013961',
    riskAllele: 'T',
  },
  {
    rsid: 'rs334',
    gene: 'HBB',
    variantDescription: 'p.Glu7Val (HbS / Sickle Cell)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Sickle Cell Disease / Sickle Cell Trait',
    acmgClassification: 'Tier 1',
    pubmedIds: ['1208920', '1527339'],
    clinvarId: 'VCV000015408',
    riskAllele: 'T',
  },
  {
    rsid: 'rs76151636',
    gene: 'GJB2',
    variantDescription: 'c.35delG',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 3,
    reviewStatus: 'Reviewed by expert panel',
    associatedCondition: 'Autosomal Recessive Non-Syndromic Sensorineural Deafness 1A',
    acmgClassification: 'Tier 1',
    pubmedIds: ['9140397', '11134472'],
    clinvarId: 'VCV000017006',
    riskAllele: 'D',
  },
  {
    rsid: 'rs113993960',
    gene: 'CFTR',
    variantDescription: 'p.Phe508del (DeltaF508)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 4,
    reviewStatus: 'Practice guideline',
    associatedCondition: 'Cystic Fibrosis (Autosomal Recessive)',
    acmgClassification: 'Tier 1',
    pubmedIds: ['2475911', '16835861'],
    clinvarId: 'VCV000007105',
    riskAllele: 'D',
  },
  {
    rsid: 'rs34550074',
    gene: 'MUTYH',
    variantDescription: 'p.Tyr179Cys (Y179C)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 3,
    reviewStatus: 'Reviewed by expert panel',
    associatedCondition: 'MUTYH-Associated Polyposis / Colorectal Cancer Susceptibility',
    acmgClassification: 'ACMG Secondary Finding',
    pubmedIds: ['11818962', '15184898'],
    clinvarId: 'VCV000005299',
    riskAllele: 'G',
  },
  {
    rsid: 'rs36053993',
    gene: 'MUTYH',
    variantDescription: 'p.Gly396Asp (G396D)',
    clinicalSignificance: 'Pathogenic',
    reviewStars: 3,
    reviewStatus: 'Reviewed by expert panel',
    associatedCondition: 'MUTYH-Associated Polyposis / Colorectal Cancer Susceptibility',
    acmgClassification: 'ACMG Secondary Finding',
    pubmedIds: ['11818962', '15184898'],
    clinvarId: 'VCV000005300',
    riskAllele: 'A',
  }
];
