import { PRSCatalogModel } from '@/types/genomics';

export const CURATED_PRS_MODELS: PRSCatalogModel[] = [
  {
    id: 'PGS000013_CAD',
    traitName: 'Coronary Artery Disease (CAD)',
    category: 'Cardiovascular',
    publication: 'Khera et al. Genome-wide polygenic scores for common diseases. Nature Genetics 2018.',
    pubmedId: '30104762',
    referenceWeights: [
      {
        rsid: 'rs10757274',
        chr: '9',
        pos: 22124477,
        gene: 'CDKN2A / CDKN2B / ANRIL',
        consequence: 'Intergenic / Enhancer',
        biologicalMechanism: 'Major 9p21.3 CAD locus. Disrupts enhancer regulatory element controlling ANRIL lncRNA expression, promoting vascular smooth muscle proliferation and atherogenesis.',
        effectAllele: 'G',
        otherAllele: 'A',
        weight: 0.174,
        referenceAlleleFreqEUR: 0.48,
      },
      {
        rsid: 'rs1333049',
        chr: '9',
        pos: 22115503,
        gene: '9p21.3 Locus',
        consequence: 'Intergenic',
        biologicalMechanism: 'Highest-ranked common genetic risk factor for myocardial infarction, coronary calcification, and abdominal aortic aneurysm.',
        effectAllele: 'C',
        otherAllele: 'G',
        weight: 0.168,
        referenceAlleleFreqEUR: 0.49,
      },
      {
        rsid: 'rs6903956',
        chr: '6',
        pos: 12903930,
        gene: 'EDN1 / PHACTR1',
        consequence: 'Intronic / Regulatory',
        biologicalMechanism: 'Modulates PHACTR1 transcriptional activity in vascular endothelial cells, altering endothelin-1 vasoactive response and coronary spasm risk.',
        effectAllele: 'A',
        otherAllele: 'G',
        weight: 0.125,
        referenceAlleleFreqEUR: 0.38,
      },
      {
        rsid: 'rs20455',
        chr: '1',
        pos: 109817590,
        gene: 'CELSR2 / SORT1',
        consequence: 'Intronic / Regulatory',
        biologicalMechanism: 'Alters hepatic SORT1 (sortilin) expression, affecting hepatic VLDL secretion and circulating plasma LDL cholesterol concentrations.',
        effectAllele: 'G',
        otherAllele: 'A',
        weight: 0.118,
        referenceAlleleFreqEUR: 0.19,
      },
      {
        rsid: 'rs17465637',
        chr: '1',
        pos: 64796338,
        gene: 'MIA3',
        consequence: 'Intronic',
        biologicalMechanism: 'Affects MIA3 (melanoma inhibitory activity protein 3), an essential factor for collagen VII export from endoplasmic reticulum in atherosclerotic plaque stability.',
        effectAllele: 'C',
        otherAllele: 'A',
        weight: 0.112,
        referenceAlleleFreqEUR: 0.72,
      },
      {
        rsid: 'rs1122608',
        chr: '19',
        pos: 11200088,
        gene: 'LDLR',
        consequence: 'Intronic / eQTL',
        biologicalMechanism: 'Regulates Low-Density Lipoprotein Receptor (LDLR) expression, modifying hepatic LDL clearance rate from bloodstream.',
        effectAllele: 'T',
        otherAllele: 'G',
        weight: 0.134,
        referenceAlleleFreqEUR: 0.23,
      },
      {
        rsid: 'rs9982601',
        chr: '21',
        pos: 35677370,
        gene: 'SLC5A3 / MRPS6',
        consequence: 'Intergenic',
        biologicalMechanism: 'Associated with early-onset coronary atherosclerosis and altered cellular inositol transport in vascular tissue.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.106,
        referenceAlleleFreqEUR: 0.16,
      },
      {
        rsid: 'rs646776',
        chr: '1',
        pos: 109822166,
        gene: 'CELSR2 / PSRC1',
        consequence: '3\' UTR / Regulatory',
        biologicalMechanism: 'Part of the 1p13 cholesterol locus linked to reduced hepatic LDL clearance and increased lifelong coronary artery disease burden.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.141,
        referenceAlleleFreqEUR: 0.78,
      },
      {
        rsid: 'rs2259816',
        chr: '12',
        pos: 111884608,
        gene: 'HNF1A',
        consequence: 'Intronic',
        biologicalMechanism: 'Hepatocyte Nuclear Factor 1-alpha regulator influencing hepatic C-reactive protein (CRP) levels and baseline systemic inflammatory state.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.098,
        referenceAlleleFreqEUR: 0.41,
      },
      {
        rsid: 'rs12190287',
        chr: '6',
        pos: 161010118,
        gene: 'LPA',
        consequence: 'Intronic',
        biologicalMechanism: 'Major determinant of elevated Lipoprotein(a) [Lp(a)] levels, an independent, causal, and prothrombotic risk factor for myocardial infarction and aortic stenosis.',
        effectAllele: 'C',
        otherAllele: 'T',
        weight: 0.089,
        referenceAlleleFreqEUR: 0.08,
      },
    ],
    populationStats: {
      EUR: { mean: 0.68, sd: 0.24 },
      AFR: { mean: 0.52, sd: 0.21 },
      EAS: { mean: 0.61, sd: 0.22 },
      SAS: { mean: 0.72, sd: 0.25 },
      AMR: { mean: 0.64, sd: 0.23 },
    },
  },
  {
    id: 'PGS000036_T2D',
    traitName: 'Type 2 Diabetes Mellitus',
    category: 'Metabolic',
    publication: 'Mahajan et al. Fine-mapping type 2 diabetes loci to single-variant resolution. Nature Genetics 2018.',
    pubmedId: '30297969',
    referenceWeights: [
      {
        rsid: 'rs7903146',
        chr: '10',
        pos: 114758349,
        gene: 'TCF7L2',
        consequence: 'Intronic / Open Chromatin',
        biologicalMechanism: 'Strongest known common genetic determinant of T2D. Increases open chromatin state, impairing islet GLP-1 signaling and glucose-stimulated insulin secretion.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.315,
        referenceAlleleFreqEUR: 0.30,
      },
      {
        rsid: 'rs1801282',
        chr: '3',
        pos: 12393125,
        gene: 'PPARG',
        consequence: 'Missense (p.Pro12Ala)',
        biologicalMechanism: 'Peroxisome proliferator-activated receptor gamma. Pro12 variant is less efficient at stimulating insulin-sensitizing target genes in adipocytes.',
        effectAllele: 'C',
        otherAllele: 'G',
        weight: 0.142,
        referenceAlleleFreqEUR: 0.88,
      },
      {
        rsid: 'rs5219',
        chr: '11',
        pos: 17409572,
        gene: 'KCNJ11',
        consequence: 'Missense (p.Glu23Lys)',
        biologicalMechanism: 'Kir6.2 subunit of the ATP-sensitive potassium (K_ATP) channel in beta cells. Lys23 decreases channel sensitivity to ATP closure, reducing insulin exocytosis.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.138,
        referenceAlleleFreqEUR: 0.39,
      },
      {
        rsid: 'rs7756992',
        chr: '6',
        pos: 20680193,
        gene: 'CDKAL1',
        consequence: 'Intronic',
        biologicalMechanism: 'CDK5 regulatory subunit-associated protein 1-like 1. Regulates tRNA modification required for accurate proinsulin translation and beta-cell maintenance.',
        effectAllele: 'G',
        otherAllele: 'A',
        weight: 0.155,
        referenceAlleleFreqEUR: 0.28,
      },
      {
        rsid: 'rs9939609',
        chr: '16',
        pos: 53820527,
        gene: 'FTO / IRX3',
        consequence: 'Intronic / Long-range Enhancer',
        biologicalMechanism: 'Disrupts enhancer regulating IRX3 and IRX5 in hypothalamic preadipocytes, shifting energy expenditure toward lipid storage and elevating obesity-driven insulin resistance.',
        effectAllele: 'A',
        otherAllele: 'T',
        weight: 0.146,
        referenceAlleleFreqEUR: 0.42,
      },
      {
        rsid: 'rs10830963',
        chr: '11',
        pos: 92708710,
        gene: 'MTNR1B',
        consequence: 'Intronic',
        biologicalMechanism: 'Melatonin receptor 1B. Increases MTNR1B expression in pancreatic islets, exaggerating melatonin-mediated inhibition of nocturnal insulin secretion and raising fasting glucose.',
        effectAllele: 'G',
        otherAllele: 'C',
        weight: 0.128,
        referenceAlleleFreqEUR: 0.31,
      },
      {
        rsid: 'rs13266634',
        chr: '8',
        pos: 118184783,
        gene: 'SLC30A8',
        consequence: 'Missense (p.Arg325Trp)',
        biologicalMechanism: 'Zinc transporter ZnT-8. Alters zinc ion accumulation into insulin secretory granules required for insulin hexamer crystallization and stability.',
        effectAllele: 'C',
        otherAllele: 'T',
        weight: 0.132,
        referenceAlleleFreqEUR: 0.69,
      },
      {
        rsid: 'rs4402960',
        chr: '3',
        pos: 185522784,
        gene: 'IGF2BP2',
        consequence: 'Intronic',
        biologicalMechanism: 'Insulin-like growth factor 2 mRNA-binding protein 2. Modulates translation of mRNAs involved in pancreatic islet development and cell regeneration.',
        effectAllele: 'T',
        otherAllele: 'G',
        weight: 0.119,
        referenceAlleleFreqEUR: 0.54,
      },
    ],
    populationStats: {
      EUR: { mean: 0.74, sd: 0.26 },
      AFR: { mean: 0.68, sd: 0.23 },
      EAS: { mean: 0.79, sd: 0.25 },
      SAS: { mean: 0.83, sd: 0.27 },
      AMR: { mean: 0.76, sd: 0.24 },
    },
  },
  {
    id: 'PGS000015_BRCA',
    traitName: 'Hereditary & Common Breast Cancer Risk',
    category: 'Oncology',
    publication: 'Mavaddat et al. Polygenic Risk Scores for Prediction of Breast Cancer Risk. Am J Hum Genet 2019.',
    pubmedId: '30554720',
    referenceWeights: [
      {
        rsid: 'rs2046210',
        chr: '6',
        pos: 152010271,
        gene: 'ESR1',
        consequence: 'Upstream / Regulatory',
        biologicalMechanism: 'Estrogen Receptor 1 regulatory variant modifying estrogen signaling sensitivity and ER-positive breast epithelial proliferation.',
        effectAllele: 'A',
        otherAllele: 'G',
        weight: 0.158,
        referenceAlleleFreqEUR: 0.36,
      },
      {
        rsid: 'rs3803662',
        chr: '16',
        pos: 52599187,
        gene: 'TOX3',
        consequence: 'Intronic / Regulatory',
        biologicalMechanism: 'Regulates TOX High Mobility Group Box Family Member 3, altering chromatin remodeling and DNA damage repair response in breast tissue.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.169,
        referenceAlleleFreqEUR: 0.24,
      },
      {
        rsid: 'rs13387042',
        chr: '2',
        pos: 217937517,
        gene: '2q35 Locus',
        consequence: 'Intergenic',
        biologicalMechanism: 'Modulates long-range enhancer interactions with IGFBP5, affecting apoptosis and cell cycle progression in mammary epithelium.',
        effectAllele: 'A',
        otherAllele: 'G',
        weight: 0.124,
        referenceAlleleFreqEUR: 0.50,
      },
      {
        rsid: 'rs2981582',
        chr: '10',
        pos: 123354729,
        gene: 'FGFR2',
        consequence: 'Intronic / Oct-1/Runx2 motif',
        biologicalMechanism: 'Fibroblast Growth Factor Receptor 2. Creates high-affinity transcription factor binding site that increases FGFR2 expression and constitutive growth signaling.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.147,
        referenceAlleleFreqEUR: 0.39,
      },
      {
        rsid: 'rs1219648',
        chr: '10',
        pos: 123357972,
        gene: 'FGFR2',
        consequence: 'Intronic',
        biologicalMechanism: 'Associated in linkage disequilibrium with FGFR2 promoter activation in estrogen receptor positive tumor development.',
        effectAllele: 'G',
        otherAllele: 'A',
        weight: 0.136,
        referenceAlleleFreqEUR: 0.40,
      },
      {
        rsid: 'rs4784227',
        chr: '16',
        pos: 52598159,
        gene: 'TOX3 / LOC643714',
        consequence: 'Intronic',
        biologicalMechanism: 'Promotes breast cancer susceptibility by altering transcription of neuroendocrine and mammary epithelial differentiation factors.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.151,
        referenceAlleleFreqEUR: 0.25,
      },
    ],
    populationStats: {
      EUR: { mean: 0.58, sd: 0.22 },
      AFR: { mean: 0.49, sd: 0.19 },
      EAS: { mean: 0.54, sd: 0.20 },
      SAS: { mean: 0.56, sd: 0.21 },
      AMR: { mean: 0.55, sd: 0.21 },
    },
  },
  {
    id: 'PGS000021_AFIB',
    traitName: 'Atrial Fibrillation (AFib)',
    category: 'Cardiovascular',
    publication: 'Roselli et al. Multi-ethnic genome-wide association study for atrial fibrillation. Nat Genet 2018.',
    pubmedId: '29892015',
    referenceWeights: [
      {
        rsid: 'rs2200733',
        chr: '4',
        pos: 111450201,
        gene: 'PITX2',
        consequence: 'Intergenic / Enhancer',
        biologicalMechanism: 'Top risk locus on 4q25. Enhancer modulating PITX2 expression, a master homeobox transcription factor directing pulmonary vein myocardial sleeve morphogenesis and atrial electrophysiology.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.392,
        referenceAlleleFreqEUR: 0.12,
      },
      {
        rsid: 'rs10033464',
        chr: '4',
        pos: 111440871,
        gene: 'PITX2',
        consequence: 'Intergenic',
        biologicalMechanism: 'Independent 4q25 non-coding variant associated with shortened atrial refractory period and spontaneous ectopic triggers.',
        effectAllele: 'T',
        otherAllele: 'G',
        weight: 0.285,
        referenceAlleleFreqEUR: 0.14,
      },
      {
        rsid: 'rs2106261',
        chr: '16',
        pos: 73002283,
        gene: 'ZFHX3',
        consequence: 'Intronic',
        biologicalMechanism: 'Zinc finger homeobox 3. Regulates cardiac pacemaker gene networks, calcium homeostasis, and intercellular communication via connexins.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.198,
        referenceAlleleFreqEUR: 0.19,
      },
      {
        rsid: 'rs13376333',
        chr: '1',
        pos: 154823901,
        gene: 'KCNN3',
        consequence: 'Intronic',
        biologicalMechanism: 'Potassium calcium-activated channel subfamily N member 3 (SK3 channel). Controls repolarization dynamics and action potential duration in human atrial myocytes.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.165,
        referenceAlleleFreqEUR: 0.37,
      },
    ],
    populationStats: {
      EUR: { mean: 0.42, sd: 0.21 },
      AFR: { mean: 0.29, sd: 0.16 },
      EAS: { mean: 0.38, sd: 0.19 },
      SAS: { mean: 0.40, sd: 0.20 },
      AMR: { mean: 0.39, sd: 0.19 },
    },
  },
  {
    id: 'PGS000042_ALZ',
    traitName: "Late-Onset Alzheimer's Disease & Polygenic Risk",
    category: 'Neurology',
    publication: 'Bellenguez et al. New insights into the genetic etiology of Alzheimer’s disease. Nat Genet 2022.',
    pubmedId: '35379992',
    referenceWeights: [
      {
        rsid: 'rs429358',
        chr: '19',
        pos: 44908684,
        gene: 'APOE (epsilon 4)',
        consequence: 'Missense (p.Cys130Arg)',
        biologicalMechanism: 'Primary determinant of APOE e4 isoform. Alters lipoprotein particle conformation, accelerates beta-amyloid aggregation, and reduces cerebral microglial clearance.',
        effectAllele: 'C',
        otherAllele: 'T',
        weight: 1.150,
        referenceAlleleFreqEUR: 0.15,
      },
      {
        rsid: 'rs7412',
        chr: '19',
        pos: 44908822,
        gene: 'APOE (epsilon 2)',
        consequence: 'Missense (p.Arg176Cys)',
        biologicalMechanism: 'Primary determinant of APOE e2 isoform. Confers strong neuroprotective effect and significantly reduces lifelong risk of late-onset Alzheimer\'s.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: -0.620,
        referenceAlleleFreqEUR: 0.08,
      },
      {
        rsid: 'rs6733839',
        chr: '2',
        pos: 127891244,
        gene: 'BIN1',
        consequence: 'Intergenic / Enhancer',
        biologicalMechanism: 'Bridging Integrator 1. Second most significant Alzheimer\'s risk locus. Modulates clathrin-mediated endocytosis, endosomal trafficking, and tau neurofibrillary pathology.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: 0.178,
        referenceAlleleFreqEUR: 0.40,
      },
      {
        rsid: 'rs11136000',
        chr: '8',
        pos: 27464041,
        gene: 'CLU (Clusterin)',
        consequence: 'Intronic',
        biologicalMechanism: 'Extracellular chaperone protein clusterin/ApoJ. Facilitates amyloid-beta clearance across the blood-brain barrier and suppresses neuroinflammatory apoptosis.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: -0.142,
        referenceAlleleFreqEUR: 0.36,
      },
      {
        rsid: 'rs3851179',
        chr: '11',
        pos: 85934500,
        gene: 'PICALM',
        consequence: 'Intergenic',
        biologicalMechanism: 'Phosphatidylinositol-binding clathrin assembly protein. Regulates APP internalisation and transcytosis of amyloid-beta peptides.',
        effectAllele: 'T',
        otherAllele: 'C',
        weight: -0.135,
        referenceAlleleFreqEUR: 0.47,
      },
    ],
    populationStats: {
      EUR: { mean: 0.35, sd: 0.38 },
      AFR: { mean: 0.48, sd: 0.39 },
      EAS: { mean: 0.26, sd: 0.31 },
      SAS: { mean: 0.32, sd: 0.34 },
      AMR: { mean: 0.36, sd: 0.36 },
    },
  },
];
