import React from 'react';
export function MethodsDashboard() {
  return <section className="stack prose"><div className="section-heading"><h1>Methods and limits</h1><p>What this version does, and what its results cannot establish.</p></div>
    <h2>Local processing</h2><p>The browser reads a text file or a ZIP containing one text file, validates its rows and matches marker IDs against bundled panels. File processing runs in a local worker. There is no genotype upload, live annotation request or persistent result storage.</p>
    <h2>Polygenic and cumulative risk</h2><p>Five published models cover breast cancer (PGS000001), coronary artery disease (PGS000011), type 2 diabetes (PGS000031), Alzheimer's disease excluding APOE (PGS000025), and atrial fibrillation (PGS000035). All source rows, weights and GRCh37/38 positions are archived. Each usable contribution is forward-strand effect-allele dosage (0, 1 or 2) multiplied by the published weight. Negative contributions are retained. Compensated summation reduces floating-point accumulation error.</p><p>Missing calls, unsupported builds, mismatched coordinates, unexpected alleles and unresolved reference assignments are excluded with a visible reason. All five models have unresolved source rows, so current outputs are incomplete observed subtotals, even in a fully called file. No missing value is imputed or treated as zero. JSON retains numerical precision; the table rounds only for reading.</p><p>Higher/lower odds labels describe the published effect allele, relative to its paired allele. Zero dosage is not a protective result. AFib weights have no reported unit in the Catalog, so they are labelled as score associations rather than odds. A weighted sum is not a disease probability or a comparison with the population average. No population percentiles or cumulative disease probabilities are calculated.</p>
    <h2>Drug response and clinical variants</h2><p>Star-allele calls, medication recommendations, pathogenicity and carrier-status assignments are withheld. These require verified allele definitions, adequate coverage, phasing where relevant and condition-specific evidence. A missing result does not mean a normal or negative result.</p>
    <h2>Genome coordinates</h2><p>Genome build and chip version are separate metadata. Unknown or conflicting build information stays unknown. No liftover, ancestry inference or genotype imputation is performed.</p>
    <h2>References</h2><p>These resources describe methods and data standards; citing them does not validate this app. Links open external websites.</p><ul>
      <li><a href="https://www.pgscatalog.org/" target="_blank" rel="noopener noreferrer">PGS Catalog</a>: complete scoring files and study-specific evaluations.</li>
      <li><a href="https://cpicpgx.org/" target="_blank" rel="noopener noreferrer">CPIC</a>: gene- and drug-specific guidelines.</li>
      <li><a href="https://www.ncbi.nlm.nih.gov/clinvar/" target="_blank" rel="noopener noreferrer">ClinVar</a>: variant- and condition-specific classifications.</li>
    </ul>
  </section>;
}
